### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by isaacabraham**
Fix guidance to cd into directory before dotnet restore.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Thanks you :)

**Comment by alfonsogarciacaro** [comment]
Good one! An alternative is to add a solution file so the project can be restored from root, also when you add more projects to the solution. Another thing I'm considering for the simple template is to add `"preinstall": "dotnet restore src"` to package.json scripts so users only need to run `npm/yarn install`.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Why not, but users will have to move into `src` to run `dotnet fable ....` I'm really not sure what to decide about the templates and UX.

**Comment by alfonsogarciacaro** [comment]
Yeah, another thing I'm also considering is to call Fable directly from npm scripts, so you would have something like this:

```json
"scripts": {
    "preinstall": "dotnet restore src",
    "start": "cd src && dotnet fable webpack-dev-server"
}
```

So the user only needs to run:

```shell
npm install
npm start
```

The only thing that draws me back is I want the user to know more or less how everything works, in case they need to change/fix something, so I don't like to hide too many things from them.

**Comment by MangelMaxime** [comment]
It exactly my though about `dotnet restore` etc.

If they see everything work like by magic it can create problems later when they start experimenting.

**Comment by isaacabraham** [comment]
Definitely from a ".NET" user point of view, it'd be good in the readme to have a simple diagram or something showing the relationship or pipeline between npm / yarn, webpack, dotnet restore and dotnet fable.

**Pull request merged**
