### PR TITLE
Use latest Paket

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Thanks I will publish the new templates

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime If you haven't published the template yet, can you take the chance to update Fable.Core and dotnet-fable to 1.1.5? Thanks!

**Comment by forki** [comment]
also I didn't meant to push .paket/paket.exe.config - can you please remove it? sorry

**Comment by MangelMaxime** [comment]
I will republish both according to your comments :)

**Pull request merged**
