### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
A few things I felt missing when creating FableConf web:

- Update dependencies: except for Webpack as version 3 gives problems with Fable, I need to check that
- Add package-lock.json: in case someone prefers to use NPM 5 instead of Yarn
- Add favicon: I'm not sure what's the best way to do this. Fable logo didn't look very well when minimized to 16x16 so I'm providing also a 32x32 version. Please check.
- Add meta viewport tag: This is important for mobile
- Update README

We may also consider to move the project file to the src folder as discussed in another thread. In that case we can just ask the user to move to `src` folder, or replace the `start` command in package.json like this:

```json
  "webpack-dev-server": "webpack-dev-server",
  "start": "cd src && dotnet fable npm-run webpack-dev-server"
```

The main disadvantage here is we have to pick between npm or yarn so it's not a user choice (atm, calling `yarn-run` like this would fail because there's no package.json in the `src` directory, but that will be fixed in next Fable release).

We're gonna need a template for the templates :wink:

### CODE REVIEW

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Did you say "minor" with a diff `+5,279 -64` :trollface: 

And no need to make a choice, I can add the option in the template to use npm or yarn. And generate the package.json related to each and also not include the package-lock.json as yarn don't support it for the moment.

For the other modifications I agree 👍

**Comment by alfonsogarciacaro** [comment]
Hehe, that was just because of the package-lock.json file :wink:

Ok, I just removed the npm lock file for now :+1:

**Comment by MangelMaxime** [comment]
You could let it. :)

No problem, I will re-add it when adding the tool choice :)

**Comment by alfonsogarciacaro** [comment]
Ok, great. Just be careful because the README should also if you use `npm` instead of `yarn`. Even for the `dotnet fable yarn-start` command.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Can you please check what I have done ?
If this is ok you can publish or notify me and I will do.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime I just noticed that, since you're using `cdn.polyfill.io` in the index.html, we don't need the transform-runtime Babel plugin which injects core-js polyfills, only the external-helpers. Should I change that?

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Yes if you can remove the transforme-runtime would be nice.

I personally prefer `cdn.polyfill.io` which include only what is needed for the browser. And we can configure it like we want depending on user needs.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro What do I need to remove in the package.json and perhaps into the webpack config to remove "transform-runtime" ?

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Commit https://github.com/fable-elmish/templates/pull/20/commits/9f0da421b2ca1468e8609f8f5a030470f877fcc1 should have already fixed that. The `transform-runtime` plugin is still kept for Babel helpers (so no need to remove it from package.json), if not used, Babel will introduce the same helpers for every file so there'll be some duplicated in the bundle.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Oh ok I didn't saw this lines.

Thanks, I will update the deps to latest version and publish a new version of template today so.

**Comment by alfonsogarciacaro** [comment]
Great, please note that new versions have been just published. Also, I think you can update Webpack (3.3.0) and webpack-dev-server now. But apparently you must also install `loglevel` for latest webpack-dev-server to work.

**Comment by MangelMaxime** [comment]
Ok I finally publish both package.

- React demo: 0.1..4 
- React : 0.2.6

We need to simplify the process, I have an idea because I made the same check on both templates and that's not really fun ^^. Will open an issue to discuss it.

**Pull request merged**
